name: Build and push the web server image

on:
  push:
  workflow_dispatch:

jobs:
  build-and-push-image:
    permissions:
      packages: write
      contents: read
    name: Build and push the web server image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/buonhobo/advent-of-faith:latest